services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ '/usr/src/app/entrypoint.sh' ]
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    env_file:
      - .envs/.flask.env
    depends_on:
      - api-db

  api-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - .envs/.api-db.env
